// This file is @generated by prost-build.
/// 根消息 - 用户状态 (兼容 SessionResponse)
/// 注意：大多数字段使用 bytes 以避免 wire type 错误
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionResponse {
    /// 原 int32，改为 bytes
    #[prost(bytes = "vec", tag = "5")]
    pub field_5: ::prost::alloc::vec::Vec<u8>,
    /// 认证配置 (已验证可用)
    #[prost(message, optional, tag = "6")]
    pub auth: ::core::option::Option<AuthInfo>,
    #[prost(bytes = "vec", tag = "7")]
    pub field_7: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "9")]
    pub field_9: ::prost::alloc::vec::Vec<u8>,
    /// sessions (保留为 bytes)
    #[prost(bytes = "vec", tag = "10")]
    pub field_10: ::prost::alloc::vec::Vec<u8>,
    /// ui_config (保留为 bytes)
    #[prost(bytes = "vec", tag = "11")]
    pub field_11: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "15")]
    pub field_15: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "16")]
    pub field_16: ::prost::alloc::vec::Vec<u8>,
    /// artifacts (保留为 bytes)
    #[prost(bytes = "vec", tag = "17")]
    pub field_17: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "18")]
    pub f18: ::prost::alloc::vec::Vec<u8>,
    /// 应用配置 (已验证可用)
    #[prost(message, optional, tag = "19")]
    pub context: ::core::option::Option<UserContext>,
    /// 订阅信息
    #[prost(message, optional, tag = "36")]
    pub subscription: ::core::option::Option<Subscription>,
}
/// 认证配置
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthInfo {
    /// OAuth access token
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// "Bearer"
    #[prost(string, tag = "2")]
    pub token_type: ::prost::alloc::string::String,
    /// OAuth refresh token
    #[prost(string, tag = "3")]
    pub refresh_token: ::prost::alloc::string::String,
    /// 创建时间
    #[prost(message, optional, tag = "4")]
    pub created_at: ::core::option::Option<Timestamp>,
}
/// 时间戳
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Timestamp {
    /// Unix 时间戳秒数
    #[prost(int64, tag = "1")]
    pub seconds: i64,
}
/// 某个标志消息
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SomeFlag {
    #[prost(int32, tag = "1")]
    pub value: i32,
}
/// 会话记录
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionRecord {
    /// UUID 格式
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    /// 时间戳
    #[prost(message, optional, tag = "2")]
    pub timestamp: ::core::option::Option<SessionTimestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionTimestamp {
    #[prost(int64, tag = "1")]
    pub seconds: i64,
    #[prost(int32, tag = "2")]
    pub nanos: i32,
}
/// UI 配置
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UiConfig {
    #[prost(int32, tag = "1")]
    pub field_1: i32,
    #[prost(int32, tag = "2")]
    pub field_2: i32,
}
/// Artifact 文件
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Artifact {
    /// 文件路径
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    /// 元数据
    #[prost(message, optional, tag = "2")]
    pub meta: ::core::option::Option<ArtifactMeta>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ArtifactMeta {
    /// 类型
    #[prost(int32, tag = "1")]
    pub r#type: i32,
    /// 描述
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    /// 时间戳
    #[prost(message, optional, tag = "4")]
    pub timestamp: ::core::option::Option<Timestamp>,
    /// 状态
    #[prost(int32, tag = "5")]
    pub status: i32,
}
/// 用户上下文
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserContext {
    #[prost(int32, tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub plan_name: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub email: ::prost::alloc::string::String,
    /// 模型配置
    #[prost(message, optional, tag = "33")]
    pub models: ::core::option::Option<AppConfig>,
    /// 订阅计划
    #[prost(message, optional, tag = "36")]
    pub plan: ::core::option::Option<Subscription>,
}
/// 应用配置
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppConfig {
    /// 模型配置列表
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<ModelConfig>,
    /// 推荐模型
    #[prost(message, optional, tag = "2")]
    pub recommended: ::core::option::Option<RecommendedModels>,
    /// 默认模型
    #[prost(message, optional, tag = "3")]
    pub default_model: ::core::option::Option<DefaultModel>,
}
/// 模型配置
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelConfig {
    /// 模型名称
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// 模型 ID
    #[prost(message, optional, tag = "2")]
    pub id: ::core::option::Option<ModelId>,
    /// 某个标志
    #[prost(int32, tag = "5")]
    pub field_5: i32,
    /// 某个标志
    #[prost(int32, tag = "11")]
    pub field_11: i32,
    /// 模型元数据
    #[prost(message, optional, tag = "15")]
    pub meta: ::core::option::Option<ModelMeta>,
    /// 标签 (如 "New")
    #[prost(string, tag = "16")]
    pub tag: ::prost::alloc::string::String,
    /// 支持的 MIME 类型
    #[prost(message, repeated, tag = "18")]
    pub supported_types: ::prost::alloc::vec::Vec<MimeTypeSupport>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelId {
    #[prost(int32, tag = "1")]
    pub id: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelMeta {
    /// 速率限制相关
    #[prost(float, tag = "1")]
    pub rate_limit: f32,
    #[prost(message, optional, tag = "2")]
    pub timestamp: ::core::option::Option<MetaTimestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetaTimestamp {
    #[prost(int64, tag = "1")]
    pub value: i64,
}
/// MIME 类型支持
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MimeTypeSupport {
    /// MIME 类型
    #[prost(string, tag = "1")]
    pub mime_type: ::prost::alloc::string::String,
    /// 是否启用
    #[prost(int32, tag = "2")]
    pub enabled: i32,
}
/// 推荐模型
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecommendedModels {
    /// 分类名称 "Recommended"
    #[prost(string, tag = "1")]
    pub category: ::prost::alloc::string::String,
    /// 推荐列表
    #[prost(message, optional, tag = "2")]
    pub list: ::core::option::Option<RecommendedList>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecommendedList {
    /// 模型名称列表
    #[prost(string, repeated, tag = "2")]
    pub model_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// 默认模型
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DefaultModel {
    #[prost(message, optional, tag = "1")]
    pub model: ::core::option::Option<ModelId>,
}
/// 订阅信息
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Subscription {
    /// "g1-pro-tier"
    #[prost(string, tag = "1")]
    pub tier_id: ::prost::alloc::string::String,
    /// "Google AI Pro"
    #[prost(string, tag = "2")]
    pub tier_name: ::prost::alloc::string::String,
    /// "Google AI Pro"
    #[prost(string, tag = "3")]
    pub display_name: ::prost::alloc::string::String,
    /// 升级链接
    #[prost(string, tag = "7")]
    pub upgrade_url: ::prost::alloc::string::String,
    /// 升级提示信息
    #[prost(string, tag = "8")]
    pub upgrade_message: ::prost::alloc::string::String,
}
